root = "."

[build]
cmd = "go build -o ./tmp/mdprev ."
bin = "./tmp/mdprev"
args_bin = ["--port", "8080", "--open=false", "--auto-close=false", "./example"]
include_ext = ["go"]
exclude_dir = ["tmp", "web", "node_modules"]

[misc]
clean_on_exit = true
